server:
  shutdown: graceful

spring:
  profiles:
    default: local
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    root: info
  pattern:
    console: "[%-5level][%d{yy-MM-dd HH:mm:ss.SSS}][%thread][%X{sessId}-%X{traceId}][%logger{36}][%method:%line] - %msg %n"
